[tox]
envlist =
    c1, pylint, flake8
skipsdist = true
skip_missing_interpreters = true

[tool:pytest]
testpaths = tests

[coverage:run]
source =
    db
    routers
    tasks
    utils
    services
    # validation

[testenv]
passenv = LANG
deps =
    pytest
    pytest-cov
    -rrequirements.txt
    -rrequirements.dev.txt
envlogdir = {toxinidir}/logs
commands =
    # pytest --cov=. tests -v --cov-branch --cov-report=term --cov-report=html --cov-report=xml --basetemp={envtmpdir} {posargs}
    pytest --cov=db --cov=routers --cov=tasks --cov=utils --cov=services tests -v --cov-branch --cov-report=term --cov-report=html --cov-report=xml --basetemp={envtmpdir} {posargs} --ignore=tests/validation

[testenv:pylint]
deps =
    pylint
    -rrequirements.txt
commands = pylint db routers tasks utils services

[testenv:flake8]
deps = flake8
commands = flake8 db routers tasks utils services
